import {
  columnDefinition,
  createEnumSql,
  createRelationSql,
  createViewSql,
  functionSignature,
  isForeignKey,
  qualified,
  quoteIdent,
  replaceViewSql,
} from "./schema-ddl";
import type { DiffObject, SchemaDiff } from "./schema-diff";
import type { SnapshotColumn, SnapshotRelation } from "./types";

export type MigrationOptions = {
  sourceName: string;
  targetName: string;
  /** DROP statements are withheld unless this is on. */
  includeDrops: boolean;
};

export type Migration = {
  sql: string;
  /** Executable statements, ignoring comments. */
  statements: number;
  /** Changes that cannot be expressed as a statement and are left as a comment. */
  manual: number;
};

type Bucket =
  | "extension"
  | "schema"
  | "enum"
  | "table"
  | "constraint"
  | "alter"
  | "view"
  | "function"
  | "trigger";

const BUCKETS: { id: Bucket; title: string }[] = [
  { id: "extension", title: "Extensions" },
  { id: "schema", title: "Schemas" },
  { id: "enum", title: "Types" },
  { id: "table", title: "New tables" },
  { id: "constraint", title: "Foreign keys" },
  { id: "alter", title: "Table changes" },
  { id: "view", title: "Views" },
  { id: "function", title: "Functions" },
  { id: "trigger", title: "Triggers" },
];

/** A block of statements for one object, kept together under its own comment. */
type Block = { bucket: Bucket; title: string; lines: string[] };

type Draft = {
  blocks: Block[];
  drops: Block[];
  manual: number;
};

/**
 * Writes the DDL that would bring the target database in line with the source.
 * Nothing here is executed: the output is a script to read, edit, and run
 * through the migration tool the project already uses.
 */
export function buildMigration(diff: SchemaDiff, options: MigrationOptions): Migration {
  const draft: Draft = { blocks: [], drops: [], manual: 0 };
  for (const object of diff.objects) migrateObject(object, draft, options);

  const sections: string[] = [];
  for (const bucket of BUCKETS) {
    const blocks = draft.blocks.filter((block) => block.bucket === bucket.id);
    if (blocks.length === 0) continue;
    sections.push([`-- ${bucket.title}`, ...blocks.map(renderBlock)].join("\n\n"));
  }

  if (draft.drops.length > 0) {
    if (options.includeDrops) {
      sections.push(
        [
          `-- Drops — objects only in ${options.targetName}`,
          ...draft.drops.map(renderBlock),
        ].join("\n\n"),
      );
    } else {
      const count = draft.drops.length;
      sections.push(
        `-- ${count} object${count === 1 ? "" : "s"} exist only in ${options.targetName}.\n` +
          `-- Turn on "Include drops" to generate the DROP statements for them.`,
      );
    }
  }

  const body = sections.join("\n\n");
  const statements = countStatements(body);
  const header = [
    `-- Schema migration generated by YTDB`,
    `-- Apply to ${options.targetName} so it matches ${options.sourceName}`,
    statements === 0
      ? `-- Nothing to apply`
      : `-- ${statements} statement${statements === 1 ? "" : "s"} — review before running`,
  ].join("\n");

  return {
    sql: body ? `${header}\n\n${body}\n` : `${header}\n`,
    statements,
    manual: draft.manual,
  };
}

function renderBlock(block: Block): string {
  return [`-- ${block.title}`, ...block.lines].join("\n");
}

function countStatements(sql: string): number {
  return sql
    .split("\n")
    .filter((line) => !line.trimStart().startsWith("--"))
    .join("\n")
    .split(";")
    .filter((statement) => statement.trim().length > 0).length;
}

function migrateObject(object: DiffObject, draft: Draft, options: MigrationOptions): void {
  switch (object.category) {
    case "extension":
      return migrateExtension(object, draft, options);
    case "schema":
      return migrateSchema(object, draft);
    case "enum":
      return migrateEnum(object, draft, options);
    case "relation":
      return migrateRelation(object, draft, options);
    case "function":
      return migrateFunction(object, draft);
    default: {
      const _exhaustive: never = object;
      return _exhaustive;
    }
  }
}

function migrateExtension(
  object: Extract<DiffObject, { category: "extension" }>,
  draft: Draft,
  options: MigrationOptions,
): void {
  if (object.status === "added") {
    draft.blocks.push({
      bucket: "extension",
      title: `${object.name} — only in ${options.sourceName}`,
      lines: [`CREATE EXTENSION IF NOT EXISTS ${quoteIdent(object.name)};`],
    });
    return;
  }
  if (object.status === "removed") {
    draft.drops.push({
      bucket: "extension",
      title: object.name,
      lines: [`DROP EXTENSION IF EXISTS ${quoteIdent(object.name)};`],
    });
    return;
  }
  const version = object.details.find((detail) => detail.name === "version");
  if (version?.source) {
    draft.blocks.push({
      bucket: "extension",
      title: `${object.name} — ${version.target} → ${version.source}`,
      lines: [`ALTER EXTENSION ${quoteIdent(object.name)} UPDATE TO '${version.source}';`],
    });
  }
}

function migrateSchema(
  object: Extract<DiffObject, { category: "schema" }>,
  draft: Draft,
): void {
  if (object.status === "added") {
    draft.blocks.push({
      bucket: "schema",
      title: object.name,
      lines: [`CREATE SCHEMA IF NOT EXISTS ${quoteIdent(object.name)};`],
    });
    return;
  }
  if (object.status === "removed") {
    draft.drops.push({
      bucket: "schema",
      title: object.name,
      lines: [`DROP SCHEMA IF EXISTS ${quoteIdent(object.name)};`],
    });
  }
}

function migrateEnum(
  object: Extract<DiffObject, { category: "enum" }>,
  draft: Draft,
  options: MigrationOptions,
): void {
  if (object.status === "added" && object.source) {
    draft.blocks.push({
      bucket: "enum",
      title: `${object.label} — only in ${options.sourceName}`,
      lines: [createEnumSql(object.source)],
    });
    return;
  }
  if (object.status === "removed" && object.target) {
    draft.drops.push({
      bucket: "enum",
      title: object.label,
      lines: [`DROP TYPE IF EXISTS ${qualified(object.target)};`],
    });
    return;
  }

  const lines: string[] = [];
  const type = object.source ?? object.target;
  if (!type) return;
  for (const detail of object.details) {
    if (detail.status === "added") {
      lines.push(
        `ALTER TYPE ${qualified(type)} ADD VALUE IF NOT EXISTS '${detail.name.replace(/'/g, "''")}';`,
      );
    } else {
      draft.manual += 1;
      lines.push(
        `-- '${detail.name}' exists only in ${options.targetName}; removing an enum value means recreating the type.`,
      );
    }
  }
  if (lines.length > 0) {
    draft.blocks.push({ bucket: "enum", title: object.label, lines });
  }
}

function migrateRelation(
  object: Extract<DiffObject, { category: "relation" }>,
  draft: Draft,
  options: MigrationOptions,
): void {
  if (object.status === "added" && object.source) {
    return createRelation(object.source, draft, options);
  }
  if (object.status === "removed" && object.target) {
    return dropRelation(object.target, draft);
  }

  const source = object.source;
  const target = object.target;
  if (!source || !target) return;

  if (source.kind !== target.kind) {
    draft.manual += 1;
    draft.blocks.push({
      bucket: "alter",
      title: object.label,
      lines: [
        `-- ${object.label} is a ${target.kind} in ${options.targetName} and a ${source.kind} in ${options.sourceName}; recreate it by hand.`,
      ],
    });
    return;
  }

  if (source.kind === "view" || source.kind === "materialized view") {
    return alterView(object.label, source, draft, options);
  }

  const table = qualified(source);
  const alters: string[] = [];
  const indexes: string[] = [];
  const triggers: string[] = [];
  // Dropped in dependency order: a column drop would take its constraints with it.
  const dropped: Record<"trigger" | "index" | "constraint" | "column", string[]> = {
    trigger: [],
    index: [],
    constraint: [],
    column: [],
  };

  for (const detail of object.details) {
    const sourceColumn = source.columns.find((column) => column.name === detail.name);
    const targetColumn = target.columns.find((column) => column.name === detail.name);
    switch (detail.group) {
      case "column":
        if (detail.status === "added" && sourceColumn) {
          alters.push(
            `ALTER TABLE ${table} ADD COLUMN ${columnDefinition(sourceColumn, source.name)};`,
          );
        } else if (detail.status === "removed") {
          dropped.column.push(`ALTER TABLE ${table} DROP COLUMN IF EXISTS ${quoteIdent(detail.name)};`);
        } else if (sourceColumn && targetColumn) {
          const changes = alterColumn(table, sourceColumn, targetColumn);
          draft.manual += changes.manual;
          alters.push(...changes.lines);
        }
        break;
      case "constraint":
        if (detail.status === "removed") {
          dropped.constraint.push(
            `ALTER TABLE ${table} DROP CONSTRAINT IF EXISTS ${quoteIdent(detail.name)};`,
          );
        } else {
          if (detail.status === "modified") {
            alters.push(
              `ALTER TABLE ${table} DROP CONSTRAINT IF EXISTS ${quoteIdent(detail.name)};`,
            );
          }
          alters.push(
            `ALTER TABLE ${table} ADD CONSTRAINT ${quoteIdent(detail.name)} ${detail.source};`,
          );
        }
        break;
      case "index":
        if (detail.status === "removed") {
          dropped.index.push(
            `DROP INDEX IF EXISTS ${quoteIdent(source.schema)}.${quoteIdent(detail.name)};`,
          );
        } else {
          if (detail.status === "modified") {
            indexes.push(
              `DROP INDEX IF EXISTS ${quoteIdent(source.schema)}.${quoteIdent(detail.name)};`,
            );
          }
          indexes.push(withSemicolon(detail.source ?? ""));
        }
        break;
      case "trigger":
        if (detail.status === "removed") {
          dropped.trigger.push(`DROP TRIGGER IF EXISTS ${quoteIdent(detail.name)} ON ${table};`);
        } else {
          if (detail.status === "modified") {
            triggers.push(`DROP TRIGGER IF EXISTS ${quoteIdent(detail.name)} ON ${table};`);
          }
          triggers.push(withSemicolon(detail.source ?? ""));
        }
        break;
      default:
        draft.manual += 1;
        alters.push(
          `-- ${detail.name}: ${detail.target ?? "none"} → ${detail.source ?? "none"} (change it by hand).`,
        );
    }
  }

  if (alters.length > 0 || indexes.length > 0) {
    draft.blocks.push({
      bucket: "alter",
      title: object.label,
      lines: [...alters, ...indexes],
    });
  }
  if (triggers.length > 0) {
    draft.blocks.push({ bucket: "trigger", title: object.label, lines: triggers });
  }
  const drops = [...dropped.trigger, ...dropped.index, ...dropped.constraint, ...dropped.column];
  if (drops.length > 0) {
    draft.drops.push({ bucket: "alter", title: object.label, lines: drops });
  }
}

function createRelation(
  relation: SnapshotRelation,
  draft: Draft,
  options: MigrationOptions,
): void {
  const isView = relation.kind === "view" || relation.kind === "materialized view";
  draft.blocks.push({
    bucket: isView ? "view" : "table",
    title: `${relation.schema}.${relation.name} — only in ${options.sourceName}`,
    lines: [
      createRelationSql(relation),
      ...relation.indexes.map((index) => withSemicolon(index.sql)),
    ],
  });
  const foreignKeys = relation.constraints.filter((item) => isForeignKey(item.sql));
  if (foreignKeys.length > 0) {
    draft.blocks.push({
      bucket: "constraint",
      title: `${relation.schema}.${relation.name}`,
      lines: foreignKeys.map(
        (item) =>
          `ALTER TABLE ${qualified(relation)} ADD CONSTRAINT ${quoteIdent(item.name)} ${item.sql};`,
      ),
    });
  }
  if (relation.triggers.length > 0) {
    draft.blocks.push({
      bucket: "trigger",
      title: `${relation.schema}.${relation.name}`,
      lines: relation.triggers.map((trigger) => withSemicolon(trigger.sql)),
    });
  }
}

function dropRelation(relation: SnapshotRelation, draft: Draft): void {
  const keyword =
    relation.kind === "materialized view"
      ? "MATERIALIZED VIEW"
      : relation.kind === "view"
        ? "VIEW"
        : relation.kind === "foreign table"
          ? "FOREIGN TABLE"
          : "TABLE";
  draft.drops.push({
    bucket: "table",
    title: `${relation.schema}.${relation.name}`,
    lines: [`DROP ${keyword} IF EXISTS ${qualified(relation)};`],
  });
}

function alterView(
  label: string,
  source: SnapshotRelation,
  draft: Draft,
  options: MigrationOptions,
): void {
  if (source.kind === "view") {
    draft.blocks.push({ bucket: "view", title: label, lines: [replaceViewSql(source)] });
    return;
  }
  if (options.includeDrops) {
    draft.blocks.push({
      bucket: "view",
      title: `${label} — recreated, which discards its stored rows`,
      lines: [`DROP MATERIALIZED VIEW IF EXISTS ${qualified(source)};`, createViewSql(source)],
    });
    return;
  }
  draft.manual += 1;
  draft.blocks.push({
    bucket: "view",
    title: label,
    lines: [
      `-- The materialized view differs. Recreating it discards its stored rows,`,
      `-- so turn on "Include drops" to generate the DROP and CREATE.`,
    ],
  });
}

function migrateFunction(
  object: Extract<DiffObject, { category: "function" }>,
  draft: Draft,
): void {
  if (object.status === "removed" && object.target) {
    const keyword = object.target.kind === "procedure" ? "PROCEDURE" : "FUNCTION";
    draft.drops.push({
      bucket: "function",
      title: object.label,
      lines: [`DROP ${keyword} IF EXISTS ${functionSignature(object.target)};`],
    });
    return;
  }
  if (!object.source) return;
  draft.blocks.push({
    bucket: "function",
    title: object.label,
    lines: [withSemicolon(object.source.sql)],
  });
}

function alterColumn(
  table: string,
  source: SnapshotColumn,
  target: SnapshotColumn,
): { lines: string[]; manual: number } {
  const column = quoteIdent(source.name);
  const lines: string[] = [];
  let manual = 0;

  if (source.generated !== target.generated) {
    manual += 1;
    lines.push(
      `-- ${source.name}: a generated column cannot be altered in place; drop and re-add it.`,
    );
    return { lines, manual };
  }

  if (source.type !== target.type || source.collation !== target.collation) {
    const collate = source.collation ? ` COLLATE ${quoteIdent(source.collation)}` : "";
    lines.push(
      `ALTER TABLE ${table} ALTER COLUMN ${column} TYPE ${source.type}${collate} USING ${column}::${source.type};`,
    );
  }
  if (source.nullable !== target.nullable) {
    lines.push(
      `ALTER TABLE ${table} ALTER COLUMN ${column} ${source.nullable ? "DROP" : "SET"} NOT NULL;`,
    );
  }
  if (source.identity !== target.identity) {
    if (source.identity === null) {
      lines.push(`ALTER TABLE ${table} ALTER COLUMN ${column} DROP IDENTITY IF EXISTS;`);
    } else if (target.identity === null) {
      lines.push(
        `ALTER TABLE ${table} ALTER COLUMN ${column} ADD GENERATED ${source.identity} AS IDENTITY;`,
      );
    } else {
      lines.push(`ALTER TABLE ${table} ALTER COLUMN ${column} SET GENERATED ${source.identity};`);
    }
  }
  if (source.default !== target.default) {
    lines.push(
      source.default === null
        ? `ALTER TABLE ${table} ALTER COLUMN ${column} DROP DEFAULT;`
        : `ALTER TABLE ${table} ALTER COLUMN ${column} SET DEFAULT ${source.default};`,
    );
  }
  return { lines, manual };
}

function withSemicolon(sql: string): string {
  const trimmed = sql.trim();
  return trimmed.endsWith(";") ? trimmed : `${trimmed};`;
}
